### ISSUE TITLE
TileMap Test Error

### ISSUE THREAD

**Issue by suhanlee** [cocos2d/cocos2d-js-tests#208]
hi.

When I clicked TileMap Test Menu in sample(engine test case),
error message appeared(Error message is "Uncaught TypeError: Cannot call method 'isLoaded' of null ") and do not work properly.

is it fixing? or How could I get sample code fixed?

Environment is...
Python server(SimpleHTTPServer)
chrome web browser

**Comment by dingpinglv** [comment]
Hi, suhanlee

I just fixed this issue, the detail at https://github.com/cocos2d/cocos2d-html5/pull/1129 .

Please pull the "develop" branch of Cocos2d-html5 from https://github.com/cocos2d/cocos2d-html5
and try again.

Thanks for your feedback.
