### ISSUE TITLE
Requirejs and other concerns

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-js-tests#97]
I have a few questions about your project. 
1. How is the speed with the js bindings method compared to that of LUA and coronas 2d. Are there bench marks on this?
2. What features and OS does it support from what I see its js web and ios so far.
3. Are you using requirejs style imports? If so why cant all the code be in an amd wrapper for dependacy injection.

**Comment by linshun** [comment]
1. We had tested JSB and compared to native cocos2d. If only create some actions and run them, the performance is almost the same. We will do more bench marks later.
2. It supports all the platforms that cocos2d-iphone and cocos2d-x supported, such as iOS, Mac, Android, Windows, BlackBerry and so on
3. We don't recommend lots of js files for release or publishing in Cocos2d-html5. It is supported in JSB.

**Comment by ghost** [comment]
Awesome this is really great work! I noticed that its using native code for importing the JS with the require() I am trying to figure out how to do js dependacy management on your framework and how I can make it more modular. For web js I use AMD modules "with great success!!!" then my build script concats all my files together using grunt task build system with the requirejs task, then it swaps in almond js which is a light weight drop in replacement for requirejs that gives you dependacy management. I notice you have spidermonkey on the site the grunt task for require uses esprima which uses the spidermonkey format to find dependacys in the files so what I am thinking is we might be able to use the spidermonkey code to resolve the dependacys throw them in a array then throw in a smaller version of almond to support the AMD module format. Any ideas on any other ways to tackle this?

https://github.com/jrburke/almond/blob/master/almond.js

https://github.com/ariya/esprima

https://github.com/asciidisco/grunt-requirejs/blob/master/lib/almondify.js
